server.port: 8082

# starter-web or jpa is using logback with slf4j as implementation
logging:
  # default logging goes to console
  level:
    root: INFO
    org.springframework: ERROR
    com.edc.pps.catalog: INFO
  file:
    name: book-catalog-service/logs/boot.log
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER
    username: sa
    password:
  h2.console.enabled: true # the JDBC URL is jdbc:h2:mem:testdb
