
# starter-web or jpa is using logback with slf4j as implementation
logging:
  # default logging goes to console
  level:
    root: INFO
    org.springframework: ERROR
    com.edc.pps.catalog: INFO
  file:
    name: book-catalog-service/logs/boot.log
