server.port: 8081
server.address: 0.0.0.0

logging:
  file:
    name: book-catalog-service/logs/boot.log
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER
    username: sa
    password:
  h2.console.enabled: true # the JDBC URL is jdbc:h2:mem:testdb
  mvc:
    path match:
      matching-strategy: ant_path_matcher

management.endpoints.web.exposure.include: "*"