# server port
server.port: 8084
server.address: 0.0.0.0

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: password
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        globally_quoted_identifiers=true:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: false
  # access console http://localhost:8084/h2-console
  h2.console.enabled: true # the JDBC URL is jdbc:h2:mem:db

# spring boot actuator configuration

# enable all endpoints
management.endpoints.web.exposure.include: "*"

# disable endpoints
#management.endpoints.web.exposure.exclude: health,info,env,beans
